###############################################################################
#   @author         :   Carrick Mortimer
#   @date           :   14/07/2018
#   @package        :   
#   @description    :   
#   @url            :   
###############################################################################
homeassistant:
#  customize:

group:

    
input_number:

input_select:

input_boolean:


sensor:

###############################################################################
#                               Automations
###############################################################################
automation:
- id: movement_night_hall_light_on
  alias: Turn on hallway light red at night.
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001dc11e8
    from: 'off'
    to: 'on'
  condition:
    # Assume people are up and lights are on.
    -  condition: numeric_state
       entity_id: sensor.illumination_7811dcdee975
       below: 200
    # assume we arnt coming home from somewhere
    -  condition: state
       entity_id: binary_sensor.motion_sensor_158d0001a9e425
       state: 'off'
    # only do at night
    -  condition: template
       value_template: "{{ -9.0 > states.sun.sun.attributes.elevation }}"
#    -  condition: time
#       after: '21:00:00'
#       before: '07:00:00'
  action:
    service: light.lifx_effect_pulse
    data:
      entity_id: light.hallway_door
      period: 180
      mode: solid
      color_name: red
      cycles: 1
      brightness: 25
      power_on: True


- id: no_movement_hall_light_off
  alias: Set light back to original settings
  trigger:
    platform: sun
    event: sunrise
    offset: '+01:00:00'
  action:
    service: light.lifx_set_state
    data:
      entity_id: light.hallway_door
      brightness: 100
      kelvin: 2700
