
###############################################################################
#   @author         :   Carrick Mortimer
#   @date           :   18/07/2018
#   @package        :   
#   @description    :   Control the Ayla room temp
#   @url            :   
###############################################################################
homeassistant:
#  customize:

group:

input_number:

input_select:

sensor:

###############################################################################
#                               Automations
###############################################################################
automation:
- id: lifx_party_mode
  alias: "Turn Lifx Party Mode On"
  initial_state: 'off'
  trigger:
    - platform: time
      seconds: '/3'
  condition:
    - condition: state
      entity_id: input_boolean.partymode
      state: 'on'
  action:
    - service: light.turn_on
      entity_id: light.lounge_stereo
      data_template:
        rgb_color: ['{{ (range(0, 255)|random) }}', '{{ (range(0, 255)|random) }}', '{{ (range(0, 255)|random) }}']
        brightness: 200
        transition: '{{ (range(1, 2)|random) }}'
    - service: light.turn_on
      entity_id: light.lounge_mid
      data_template:
        rgb_color: ['{{ (range(0, 255)|random) }}', '{{ (range(0, 255)|random) }}', '{{ (range(0, 255)|random) }}']
        brightness: 200
        transition: '{{ (range(1, 2)|random) }}'
    - service: light.turn_on
      entity_id: light.lounge_rear
      data_template:
        rgb_color: ['{{ (range(0, 255)|random) }}', '{{ (range(0, 255)|random) }}', '{{ (range(0, 255)|random) }}']
        brightness: 200
        transition: '{{ (range(1, 2)|random) }}'


- id: lifx_party_mode_off
  alias: "Turn Lifx Party Mode Off"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.partymode
      to: 'off'
  action:
    - service: light.turn_on
      entity_id: group.lounge_lights
      data:
        rgb_color: [255, 255, 255]
        brightness: 250
